<div>
    <button id="sales_channel_test_connect_btn" class="action-default" type="button">
        <span><?= $block->escapeHtmlAttr("Test Connection") ?></span>
    </button>
</div>

<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('#sales_channel_test_connect_btn').click(function() {
                $.ajax({
                    url: '<?= $block->escapeUrl($block->getAjaxCheckUrl()) ?>',
                    type: 'POST',
                    dataType: 'json',
                    showLoader: true,
                    data: {
                        form_key: FORM_KEY
                    },
                    success: function(response) {
                        window.location.reload();
                    }
                });
            });
        });
    });
</script>